name: Tests

on:
  push:
  pull_request:

jobs:
  linux_tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php:
          - '8.5'

    name: PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction

      - name: Run test suite
        run: make test

      - name: Run static analysis
        run: make phpstan

      - name: Run rector
        run: make rector-dry-run

      - name: Run phpcs analysis
        run: make phpcs
