name: Tests

on:
  push:
  pull_request:

jobs:
  linux_tests:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: true
      matrix:
        php:
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'

    name: PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction

      - name: Run test suite
        run: composer run-script test

      - name: Run static analysis
        run: composer run-script phpstan

      - name: Run rector
        run: composer run-script rector-dry-run

      - name: Run phpcs analysis
        run: composer run-script phpcs
